// Module: S2alloc.obj
// Source: C:\Copter\source\common\S2alloc.c
// autogenerated by simcopter_tool from PDB file

// Type: int32_t;

// Type: unsigned long;

// Type: struct alloc_handle_t (forward reference);

// Type: char *;

// Type: struct alloc_hdr_s (forward reference);

// Type: unsigned short;

// Type: void;

// Type: void * __ptr32;



// Contribution: 1:000ca2b0-000ca878 Module: 91, 16 byte alignment, code, execute, read, 
// FUNCTION: COPTER_D 0x004cb2b0
struct alloc_handle_t* S2AllocInit(int32_t index, unsigned long poolsize) {
	struct alloc_handle_t* old;

// LINE 268:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    old, eax;
// LINE 270:
	__asm        push   8;
	__asm        call   malloc;
	__asm        add    esp, 4;
	__asm        mov    ecx, index;
	__asm        mov    [ecx*4+0x6069D8], eax;
// LINE 272:
	__asm        add    dword ptr ds:[0x59B524], 8;
	__asm        mov    eax, ds:[0x59B524];
	__asm        cmp    ds:[0x59B52C], eax;
	__asm        jae    _T4c;

	__asm        mov    eax, ds:[0x59B524];
	__asm        mov    ds:[0x59B52C], eax;
// LINE 274:
_T4c:
	__asm        mov    eax, poolsize;
	__asm        push   eax;
	__asm        call   S2AllocHdr;
	__asm        add    esp, 4;
	__asm        mov    ecx, index;
	__asm        mov    ecx, [ecx*4+0x6069D8];
	__asm        mov    [ecx], eax;
// LINE 276:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        cmp    dword ptr [eax], 0;
	__asm        je     _T90;
// LINE 277:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    eax, [eax];
	__asm        mov    ecx, index;
	__asm        mov    ecx, [ecx*4+0x6069D8];
	__asm        mov    [ecx+4], eax;
// LINE 279:
_T90:
	__asm        mov    eax, old;
	__asm        jmp    near ptr 0x004CB348;
// LINE 280:
}

// FUNCTION: COPTER_D 0x004cb34d
struct alloc_hdr_s* S2AllocHdr(unsigned long size) {
	char * block;
	struct alloc_hdr_s* hdr;

// LINE 238:
	__asm        mov    eax, size;
	__asm        push   eax;
	__asm        call   malloc;
	__asm        add    esp, 4;
	__asm        mov    block, eax;
// LINE 239:
	__asm        push   0x10;
	__asm        call   malloc;
	__asm        add    esp, 4;
	__asm        mov    hdr, eax;
// LINE 241:
	__asm        cmp    hdr, 0;
	__asm        je     _T39;

	__asm        cmp    block, 0;
	__asm        jne    _T59;
// LINE 243:
_T39:
	__asm        push   0x59B53C;
	__asm        mov    eax, 0x5C0BF8;
	__asm        add    eax, 0x40;
	__asm        push   eax;
	__asm        call   fprintf;
	__asm        add    esp, 8;
// LINE 244:
	__asm        push   1;
	__asm        call   exit;
	__asm        add    esp, 4;
// LINE 246:
_T59:
	__asm        mov    eax, block;
	__asm        mov    ecx, hdr;
	__asm        mov    [ecx+4], eax;
// LINE 247:
	__asm        mov    eax, block;
	__asm        mov    ecx, hdr;
	__asm        mov    [ecx+8], eax;
// LINE 248:
	__asm        mov    eax, hdr;
	__asm        mov    dword ptr [eax], 0;
// LINE 249:
	__asm        mov    eax, size;
	__asm        add    eax, block;
	__asm        mov    ecx, hdr;
	__asm        mov    [ecx+0xC], eax;
// LINE 251:
	__asm        mov    eax, size;
	__asm        add    eax, 0x10;
	__asm        add    ds:[0x59B524], eax;
	__asm        mov    eax, ds:[0x59B524];
	__asm        cmp    ds:[0x59B52C], eax;
	__asm        jae    _Ta7;

	__asm        mov    eax, ds:[0x59B524];
	__asm        mov    ds:[0x59B52C], eax;
// LINE 253:
_Ta7:
	__asm        mov    eax, hdr;
	__asm        jmp    near ptr 0x004CB3FC;
// LINE 254:
}

// FUNCTION: COPTER_D 0x004cb401
int32_t S2AllocPool(unsigned long poolsize) {
	int32_t index;
	struct alloc_handle_t* lastPool;

// LINE 295:
	__asm        cmp    dword ptr ds:[0x59B534], 0x20;
	__asm        jne    _T20;
// LINE 296:
	__asm        mov    eax, 0xFFFFFFFF;
	__asm        jmp    _Ta6;
// LINE 299:
_T20:
	__asm        mov    index, 0;
	__asm        jmp    _T2f;
_T2c:
	__asm        inc    index;
_T2f:
	__asm        cmp    index, 0x20;
	__asm        jge    _T54;
// LINE 301:
	__asm        mov    eax, index;
	__asm        cmp    dword ptr [eax*4+0x6069D8], 0;
	__asm        jne    _T4f;
// LINE 302:
	__asm        jmp    _T54;
// LINE 303:
_T4f:
	__asm        jmp    _T2c;
// LINE 305:
_T54:
	__asm        cmp    index, 0x20;
	__asm        jne    _T68;
// LINE 306:
	__asm        mov    eax, 0xFFFFFFFF;
	__asm        jmp    _Ta6;
// LINE 308:
_T68:
	__asm        mov    eax, poolsize;
	__asm        push   eax;
	__asm        mov    eax, index;
	__asm        push   eax;
	__asm        call   S2AllocInit;
	__asm        add    esp, 8;
	__asm        mov    lastPool, eax;
// LINE 310:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        cmp    dword ptr [eax], 0;
	__asm        jne    _T98;
// LINE 311:
	__asm        mov    eax, 0xFFFFFFFF;
	__asm        jmp    _Ta6;
// LINE 313:
_T98:
	__asm        inc    dword ptr ds:[0x59B534];
// LINE 314:
	__asm        mov    eax, index;
	__asm        jmp    _Ta6;
// LINE 315:
_Ta6:
}

// FUNCTION: COPTER_D 0x004cb4ac
char * S2Alloc(int32_t index, int32_t size) {
	struct alloc_hdr_s* hdr;
	char * ptr;

// LINE 331:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    eax, [eax+4];
	__asm        mov    hdr, eax;
// LINE 340:
	__asm        mov    eax, size;
	__asm        add    eax, 3;
	__asm        and    eax, 0xFFFFFFFC;
	__asm        mov    size, eax;
// LINE 342:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax+8];
	__asm        mov    ptr, eax;
// LINE 343:
	__asm        mov    eax, size;
	__asm        mov    ecx, hdr;
	__asm        add    [ecx+8], eax;
// LINE 347:
	__asm        mov    eax, hdr;
	__asm        mov    ecx, hdr;
	__asm        mov    ecx, [ecx+0xC];
	__asm        cmp    [eax+8], ecx;
	__asm        jb     _Te9;
// LINE 351:
	__asm        mov    eax, hdr;
	__asm        cmp    dword ptr [eax], 0;
	__asm        je     _T7c;
// LINE 354:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax];
	__asm        mov    eax, [eax+4];
	__asm        mov    ecx, hdr;
	__asm        mov    ecx, [ecx];
	__asm        mov    [ecx+8], eax;
// LINE 355:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax];
	__asm        mov    ecx, index;
	__asm        mov    ecx, [ecx*4+0x6069D8];
	__asm        mov    [ecx+4], eax;
// LINE 357:
	__asm        jmp    _Tc3;
// LINE 360:
_T7c:
	__asm        cmp    size, 0x2000;
	__asm        jle    _T9f;
// LINE 361:
	__asm        mov    eax, size;
	__asm        push   eax;
	__asm        call   S2AllocHdr;
	__asm        add    esp, 4;
	__asm        mov    ecx, hdr;
	__asm        mov    [ecx], eax;
// LINE 362:
	__asm        jmp    _Tb1;
// LINE 363:
_T9f:
	__asm        push   0x2000;
	__asm        call   S2AllocHdr;
	__asm        add    esp, 4;
	__asm        mov    ecx, hdr;
	__asm        mov    [ecx], eax;
// LINE 364:
_Tb1:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax];
	__asm        mov    ecx, index;
	__asm        mov    ecx, [ecx*4+0x6069D8];
	__asm        mov    [ecx+4], eax;
// LINE 368:
_Tc3:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    eax, [eax+4];
	__asm        mov    eax, [eax+8];
	__asm        mov    ptr, eax;
// LINE 369:
	__asm        mov    eax, size;
	__asm        mov    ecx, index;
	__asm        mov    ecx, [ecx*4+0x6069D8];
	__asm        mov    ecx, [ecx+4];
	__asm        add    [ecx+8], eax;
// LINE 372:
_Te9:
	__asm        mov    eax, size;
	__asm        add    ds:[0x59B530], eax;
// LINE 383:
	__asm        mov    eax, ptr;
	__asm        jmp    near ptr 0x004CB5A6;
// LINE 384:
}

// FUNCTION: COPTER_D 0x004cb5ab
char * S2AllocMem1(int32_t index, char * name, int32_t size, unsigned short protMem) {
// LINE 399:
	__asm        mov    eax, size;
	__asm        push   eax;
	__asm        mov    eax, name;
	__asm        push   eax;
	__asm        mov    eax, index;
	__asm        push   eax;
	__asm        call   S2AllocMem;
	__asm        add    esp, 0xC;
	__asm        jmp    near ptr 0x004CB5CA;
// LINE 400:
}

// FUNCTION: COPTER_D 0x004cb5cf
char * S2AllocMem(int32_t index, char * name, int32_t size) {
	char * ptr;

// LINE 416:
	__asm        mov    eax, size;
	__asm        push   eax;
	__asm        mov    eax, index;
	__asm        push   eax;
	__asm        call   S2Alloc;
	__asm        add    esp, 8;
	__asm        mov    ptr, eax;
// LINE 423:
	__asm        mov    eax, ptr;
	__asm        jmp    near ptr 0x004CB5F3;
// LINE 424:
}

// FUNCTION: COPTER_D 0x004cb5f8
struct alloc_handle_t* S2AllocSetPool(int32_t index, struct alloc_handle_t* newPtr) {
	struct alloc_handle_t* old;

// LINE 438:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    old, eax;
// LINE 440:
	__asm        mov    eax, newPtr;
	__asm        mov    ecx, index;
	__asm        mov    [ecx*4+0x6069D8], eax;
// LINE 442:
	__asm        mov    eax, old;
	__asm        jmp    near ptr 0x004CB623;
// LINE 443:
}

// FUNCTION: COPTER_D 0x004cb628
void S2AllocReset(int32_t index) {
	struct alloc_hdr_s* hdr;

// LINE 459:
	__asm        mov    eax, index;
	__asm        cmp    dword ptr [eax*4+0x6069D8], 0;
	__asm        jne    _T1f;
// LINE 460:
	__asm        jmp    _T96;
// LINE 462:
_T1f:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    eax, [eax];
	__asm        mov    hdr, eax;
// LINE 463:
_T2e:
	__asm        cmp    hdr, 0;
	__asm        je     _T5d;
// LINE 465:
	__asm        xor    eax, eax;
	__asm        mov    ecx, hdr;
	__asm        mov    ecx, [ecx+8];
	__asm        mov    edx, hdr;
	__asm        sub    ecx, [edx+4];
	__asm        sub    eax, ecx;
	__asm        neg    eax;
	__asm        sub    ds:[0x59B530], eax;
// LINE 466:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax];
	__asm        mov    hdr, eax;
// LINE 467:
	__asm        jmp    _T2e;
// LINE 469:
_T5d:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    eax, [eax];
	__asm        mov    ecx, index;
	__asm        mov    ecx, [ecx*4+0x6069D8];
	__asm        mov    [ecx+4], eax;
// LINE 470:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    eax, [eax+4];
	__asm        mov    eax, [eax+4];
	__asm        mov    ecx, index;
	__asm        mov    ecx, [ecx*4+0x6069D8];
	__asm        mov    ecx, [ecx+4];
	__asm        mov    [ecx+8], eax;
// LINE 474:
_T96:
}

// FUNCTION: COPTER_D 0x004cb6c3
void S2AllocFreePool(int32_t index) {
	struct alloc_hdr_s* hdr;
	struct alloc_hdr_s* next_hdr;

// LINE 493:
	__asm        mov    eax, index;
	__asm        cmp    dword ptr [eax*4+0x6069D8], 0;
	__asm        jne    _T1f;
// LINE 494:
	__asm        jmp    _Tdd;
// LINE 496:
_T1f:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        mov    eax, [eax];
	__asm        mov    hdr, eax;
// LINE 498:
_T2e:
	__asm        cmp    hdr, 0;
	__asm        je     _T9e;
// LINE 500:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax];
	__asm        mov    next_hdr, eax;
// LINE 501:
	__asm        xor    eax, eax;
	__asm        mov    ecx, hdr;
	__asm        mov    ecx, [ecx+0xC];
	__asm        mov    edx, hdr;
	__asm        sub    ecx, [edx+4];
	__asm        sub    eax, ecx;
	__asm        neg    eax;
	__asm        sub    ds:[0x59B524], eax;
// LINE 502:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax+0xC];
	__asm        mov    ecx, hdr;
	__asm        sub    eax, [ecx+4];
	__asm        add    ds:[0x59B528], eax;
// LINE 503:
	__asm        sub    dword ptr ds:[0x59B524], 0x10;
// LINE 504:
	__asm        add    dword ptr ds:[0x59B528], 0x10;
// LINE 505:
	__asm        mov    eax, hdr;
	__asm        mov    eax, [eax+4];
	__asm        push   eax;
	__asm        call   free;
	__asm        add    esp, 4;
// LINE 506:
	__asm        mov    eax, hdr;
	__asm        push   eax;
	__asm        call   free;
	__asm        add    esp, 4;
// LINE 507:
	__asm        mov    eax, next_hdr;
	__asm        mov    hdr, eax;
// LINE 508:
	__asm        jmp    _T2e;
// LINE 509:
_T9e:
	__asm        mov    eax, index;
	__asm        mov    eax, [eax*4+0x6069D8];
	__asm        push   eax;
	__asm        call   free;
	__asm        add    esp, 4;
// LINE 510:
	__asm        sub    dword ptr ds:[0x59B524], 8;
// LINE 511:
	__asm        add    dword ptr ds:[0x59B528], 8;
// LINE 512:
	__asm        mov    eax, index;
	__asm        mov    dword ptr [eax*4+0x6069D8], 0;
// LINE 513:
	__asm        dec    dword ptr ds:[0x59B534];
// LINE 516:
	__asm        call   _heapmin;
// LINE 517:
	__asm        call   _heapchk;
// LINE 523:
_Tdd:
}

// FUNCTION: COPTER_D 0x004cb7a5
void * __ptr32 S2AllocAligned() {
// LINE 591:
	__asm        call   DOSAllocAlignedHack;
	__asm        jmp    near ptr 0x004CB7B5;
// LINE 592:
}

// FUNCTION: COPTER_D 0x004cb7ba
void * __ptr32 DOSAllocAlignedHack() {
	void * __ptr32 retaddr;

// LINE 753:
	__asm        push   0x20000;
	__asm        call   malloc;
	__asm        add    esp, 4;
	__asm        mov    retaddr, eax;
// LINE 754:
	__asm        cmp    retaddr, 0;
	__asm        jne    _T2a;
// LINE 755:
	__asm        xor    eax, eax;
	__asm        jmp    _T80;
// LINE 759:
_T2a:
	__asm        test   retaddr, 0xFFFF;
	__asm        je     _T49;
// LINE 763:
	__asm        mov    eax, retaddr;
	__asm        and    eax, 0xFFFF0000;
	__asm        mov    retaddr, eax;
// LINE 764:
	__asm        add    retaddr, 0x10000;
// LINE 767:
_T49:
	__asm        add    dword ptr ds:[0x59B524], 0x10000;
	__asm        mov    eax, ds:[0x59B524];
	__asm        cmp    ds:[0x59B52C], eax;
	__asm        jae    _T6e;

	__asm        mov    eax, ds:[0x59B524];
	__asm        mov    ds:[0x59B52C], eax;
// LINE 768:
_T6e:
	__asm        add    dword ptr ds:[0x59B530], 0x10000;
// LINE 770:
	__asm        mov    eax, retaddr;
	__asm        jmp    _T80;
// LINE 771:
_T80:
}

// FUNCTION: COPTER_D 0x004cb83f
void S2FreeAligned(void * __ptr32 mem) {
// LINE 787:
	__asm        push   0x8000;
	__asm        push   0;
	__asm        mov    eax, mem;
	__asm        push   eax;
	__asm        call   dword ptr ds:[0x6C3734];
// LINE 789:
	__asm        sub    dword ptr ds:[0x59B524], 0x10000;
// LINE 790:
	__asm        sub    dword ptr ds:[0x59B530], 0x10000;
// LINE 791:
	__asm        add    dword ptr ds:[0x59B528], 0x10000;
// LINE 797:
}



// Contribution: 3:00004524-0000454a Module: 91, 4 byte alignment, initialized_data, read, write, 
// GLOBAL: COPTER_D 0x0059b524
// G_alloc_curr
// GLOBAL: COPTER_D 0x0059b528
// G_alloc_free
// GLOBAL: COPTER_D 0x0059b52c
// G_alloc_max
// GLOBAL: COPTER_D 0x0059b530
// G_alloc_used
// LOCAL: COPTER_D 0x0059b534
// poolCount
// LOCAL: COPTER_D 0x0059b538
// S_alignmem


// Contribution: 3:0006f9d8-0006fa57 Module: 91, 8 byte alignment, uninitialized_data, read, write, 
// LOCAL: COPTER_D 0x006069d8
// root
